### PR TITLE
Skia enchantments and libjpeg update preparation

### PR DESCRIPTION
**Pull request by xNombre**

### CODE REVIEW

**Comment by neobuddy89** [comment]
Is this tested? There was weird issue of image getting distorted in some apps earlier.

**Comment by xNombre** [comment]
Read this: https://github.com/crdroidandroid/android_external_libjpeg-turbo/pull/4

**Comment by gwolf2u** [comment]
hows the status of this?
do we still plan to merge it?
last time it caused weird image render issues even with updated libjpeg 2.0.6

**Comment by gwolf2u** [comment]
closed until further development on this

**Pull request closed without merging**
